### ISSUE TITLE
error with npm start (poly fills)

### ISSUE THREAD

**Issue by foxjazz** [danjbrown/angular2-webpack#1]
Not sure why this error exists...
ERROR in ./src/polyfills.ts
Module build failed: TypeError: Cannot read property 'exclude' of undefined
    at applyDefaults (G:\Code\memberships\sechubMembers\node_modules\awesome-typescript-loader\src\instance.ts:266:72)
    at Object.ensureInstance (G:\Code\memberships\sechubMembers\node_modules\awesome-typescript-loader\src\instance.ts:145:5)
    at compiler (G:\Code\memberships\sechubMembers\node_modules\awesome-typescript-loader\src\index.ts:37:20)
    at Object.loader (G:\Code\memberships\sechubMembers\node_modules\awesome-typescript-loader\src\index.ts:18:18)
 @ multi polyfills

ERROR in ./src/vendor.ts
Module build failed: TypeError: Cannot read property 'exclude' of undefined
    at applyDefaults (G:\Code\memberships\sechubMembers\node_modules\awesome-typescript-loader\src\instance.ts:266:72)
    at Object.ensureInstance (G:\Code\memberships\sechubMembers\node_modules\awesome-typescript-loader\src\instance.ts:145:5)
    at compiler (G:\Code\memberships\sechubMembers\node_modules\awesome-typescript-loader\src\index.ts:37:20)
    at Object.loader (G:\Code\memberships\sechubMembers\node_modules\awesome-typescript-loader\src\index.ts:18:18)
 @ multi vendor

ERROR in ./src/main.ts
Module build failed: TypeError: Cannot read property 'exclude' of undefined
    at applyDefaults (G:\Code\memberships\sechubMembers\node_modules\awesome-typescript-loader\src\instance.ts:266:72)
    at Object.ensureInstance (G:\Code\memberships\sechubMembers\node_modules\awesome-typescript-loader\src\instance.ts:145:5)
    at compiler (G:\Code\memberships\sechubMembers\node_modules\awesome-typescript-loader\src\index.ts:37:20)
    at Object.loader (G:\Code\memberships\sechubMembers\node_modules\awesome-typescript-loader\src\index.ts:18:18)
 @ multi app

**Comment by danjbrown** [comment]
Looks like awesome-typescript-loader won't work with TypeScript > v2.0.10.

I've forced the TypeScript version in package.json and tried a fresh install; it seems to work now.
